### ISSUE TITLE
Plugin fails to load (configFile is null)

### ISSUE THREAD

**Issue by A-nonymous027** [NotThorny/Raids#1]
Console throws this error:

`18:06:24 <ERROR:PluginManager> Failed to load plugin: Raids.jar
java.lang.NullPointerException: Cannot invoke "java.net.URL.openStream()" because "configFile" is null
        at emu.grasscutter.plugin.PluginManager.loadPlugins(PluginManager.java:76)
        at emu.grasscutter.plugin.PluginManager.<init>(PluginManager.java:32)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:128)`

Editing RewardPreviewExcelConfigData.json does nothing

Running game v4.0.0 on Grasscutter v1.7.4-5ebad71e9

**Comment by NotThorny** [comment]
Must have been a building error on my side when I made the release, since plugin.json hasn't gone anywhere. I updated [the release](https://github.com/NotThorny/Raids/releases/) with a properly working jar.
